# Generated by Django 4.1.6 on 2023-03-06 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='application_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(choices=[('A', 'Applied'), ('I', 'Interviewing'), ('P', 'Previous Application')], default=('A', 'Applied'), max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
        ),
    ]
