# Generated by Django 4.1.6 on 2023-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_application_date_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_applied',
        ),
    ]
