# Generated by Django 4.1.6 on 2023-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='app_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Previous Application', 'Previous Application')], default=('Applied', 'Applied'), max_length=20),
        ),
    ]
